Entities min props and basic annotations
kor1k/final_project_group2 pull request #12
Opened 2019-03-09 08:21 UTC by yamnyk

Add all entities with properties. Still have questions about Job entity properties.
Add SprigData dependency to pom.xml
Add basic spring annotations to all entites

2019-03-09 08:44 UTC, yamnyk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Define list of all Entities in the application, define list of minimum required properties for each entity](https://trello.com/c/ZLZ6fFsb/45-define-list-of-all-entities-in-the-application-define-list-of-minimum-required-properties-for-each-entity)

2019-03-09 12:24 UTC, podolsky4 approved these changes

2019-03-09 12:54 UTC, yamnyk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Design DB Tables structure and links based on Entities present in the system](https://trello.com/c/pqY3FiQE/46-design-db-tables-structure-and-links-based-on-entities-present-in-the-system)

2019-03-14 14:58 UTC, podolsky4 requested changes
Еще некоторые атрибуты были опущены, все ради того чтобы заставить Hibernate выполнить правильный маппинг между сущностями, сущности Education и Experience нужно связать с Profile на подобии других связей между сущностями: один-ко-многим, многие-к-одному

2019-03-14 15:02 UTC, podolsky4 commented
Попробуй собрать приложение в IDE и если все будем успешно зайти в H2 консоль ("http://localhost:9000/h2") пользователь и пароль по умолчанию (user: "sa", password: "" )

2019-03-16 18:05 UTC, podolsky4 requested changes

2019-03-16 18:05 UTC, podolsky4 commented on src/main/java/ua/com/danit/entity/Profile.java
> +  @GeneratedValue(strategy = GenerationType.IDENTITY)
Аннотацию ``@GeneratedValue`` нужно убрать, id профиля не должно быть ``auto_increment``, у нас связь один-к-одному поэтому id профиля должен быть PK and FK одновременно, вот поэтому в нас стоит аннотация ``@MapsId``, она будет брать id из таблицы ``talents``

2019-03-19 10:05 UTC, podolsky4 approved these changes

2019-03-19 14:01 UTC, erom-dm approved these changes

2019-03-19 14:33 UTC, merged