Add action creator
kor1k/final_project_group2 pull request #23
Opened 2019-03-14 14:26 UTC by alexqwerty2000

@alexqwerty2000 | add action types and action creator for talent

2019-03-14 14:27 UTC, alexqwerty2000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create user actionCreator.](https://trello.com/c/be7lr6fM/90-create-user-actioncreator)

2019-03-14 14:27 UTC, alexqwerty2000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create user actionCreator.](https://trello.com/c/be7lr6fM/90-create-user-actioncreator)

2019-03-16 18:41 UTC, podolsky4 requested changes

2019-03-16 18:41 UTC, podolsky4 commented on frontend/src/actions/talentAction.js
> +import {SUGNUP_TALENT_REQUEST, SIGNUP_TALENT_SUCCESS, SIGNUP_TALENT_FAILURE} from './types'
Ошибка в signup

2019-03-16 18:41 UTC, podolsky4 commented on frontend/src/actions/talentAction.js
> +           dispatch({
Как я уже раньше писал, вынести dispatch в отдельную функцию

2019-05-06 17:01 UTC, closed without merging