@kor1k | add button as component
kor1k/final_project_group2 pull request #25
Opened 2019-03-16 11:05 UTC by kor1k

button as Component

2019-03-16 12:43 UTC, alexqwerty2000 requested changes

2019-03-16 12:43 UTC, alexqwerty2000 commented on frontend/src/components/Button/index.js
> +  handleClick = () => {
Костя handleClick  можно получать из props и название кнопки тоже можно получать из props

2019-03-16 12:43 UTC, alexqwerty2000 commented on frontend/src/components/Button/index.js
> +class Button extends React.Component {
Используй деструктуризацию props

2019-03-16 12:43 UTC, alexqwerty2000 commented on frontend/src/components/Button/index.js
> +        +{this.props.incrementValue}
Название кнопки из props с названием title и убрать + перед ней

2019-03-16 12:43 UTC, alexqwerty2000 commented on frontend/src/components/Button/index.js
> +const Result = props => {
Что делает этот Result

2019-03-16 12:43 UTC, alexqwerty2000 commented on frontend/src/components/Button/index.js
> +class App extends React.Component {
Для компонента кнопки надо добавить проверку PropTypes

2019-03-16 13:07 UTC, kor1k commented
хорошо, Лёша,  постараюсь сделать всё, что ты сказал. спасибо!

2019-03-16 13:09 UTC, kor1k commented
Лёша, я просто переписал на совсем другое

2019-03-18 10:37 UTC, podolsky4 approved these changes

2019-03-18 18:06 UTC, alexqwerty2000 approved these changes

2019-03-18 18:07 UTC, merged

2019-03-21 21:02 UTC, kor1k commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Button component](https://trello.com/c/vJq5Qc6I/118-create-button-component)