Create README.md
kor1k/final_project_group2 pull request #5
Opened 2019-03-04 16:10 UTC by kor1k

Need add text from https://neogalaxy.gitbook.io/mango . Badges, etc.

2019-03-05 11:05 UTC, yamnyk requested changes
Докидай текст с второй страницы по ссылке, которую ты указал тут и будет тебе апрув)

2019-03-05 13:02 UTC, podolsky4 reviewed
Add installation instructions to bootstrap project for newcomers

2019-03-05 17:25 UTC, kor1k commented
Всё до 18:00 06.03 будет на месте!

2019-03-06 17:19 UTC, kor1k commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create README.MD with instructions.](https://trello.com/c/UZWfDdhv/11-create-readmemd-with-instructions)

2019-03-06 17:34 UTC, kor1k commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Travis CI badge to README.MD](https://trello.com/c/lfkS5At7/13-add-travis-ci-badge-to-readmemd)

2019-03-06 18:16 UTC, yamnyk approved these changes

2019-03-06 21:08 UTC, podolsky4 commented on README.md
> +Mango is a platform for talents and companies looking for technicians.
Сделай здесь две пустые строку между бейджиками и описанием

2019-03-06 21:08 UTC, podolsky4 commented on README.md
> +#Installation instructions to bootstrap project
Здесь сделай `## Get started` и все, этого достаточно!

2019-03-06 21:08 UTC, podolsky4 commented on README.md
> + ## Stack of technologies which were used in project
Просто `Tools` будет достаточно

2019-03-07 20:34 UTC, kor1k commented on README.md
> +#Installation instructions to bootstrap project
ок, до субботы / в субботу сделаю

2019-03-07 20:34 UTC, kor1k commented on README.md
> + ## Stack of technologies which were used in project
ок, до субботы / в субботу сделаю

2019-03-09 22:42 UTC, podolsky4 approved these changes
Okay, let's leave it for now

2019-03-10 10:36 UTC, merged