alex-ivanov change application.yml  file and add to project .travis.yml file
kor1k/final_project_group2 pull request #7
Opened 2019-03-05 18:31 UTC by alexqwerty2000

2019-03-05 19:35 UTC, podolsky4 requested changes

2019-03-05 19:35 UTC, podolsky4 commented on .travis.yml
> +  - mvn clean test
Добавь также сборку fronend части приложения на Travis CI как в методичке

2019-03-06 18:38 UTC, kor1k approved these changes
ok

2019-03-06 18:41 UTC, yamnyk approved these changes
доверяю коллективному бессознательному

2019-03-06 20:48 UTC, podolsky4 approved these changes

2019-03-06 21:09 UTC, merged